/* Details of the maps used by the levels */
var maps = {
    "plains": {
        "mapImage": "plains-debug.png",
        /* Terrain Data - Auto Generated By level/convert-levels.js */
        "mapGridWidth": 60,
        "mapGridHeight": 40,
        "mapObstructedTerrain": [[0, 0], [1, 0], [2, 0], [26, 0], [27, 0], /* Extremely huge
        array snipped for brevity */ [58, 39], [59, 39]],
} };
/* The actual levels played in the game */
var levels = {
    "singleplayer": [
        {
            "name": "Introduction",
            "briefing": "In this level you will learn how to pan across the map.\n\nDon't worry! We will be implementing more features soon.",
            /* Map Details */
            "mapName": "plains",
            "startX": 4,
            "startY": 4,
} ],
    "multiplayer": [
] };